update public.achievement_definitions as achievement
set description = descriptions.description
from (
  values
    ('critical_roll', 'Jedna dwudziestka i nagle cały ten misterny plan przestaje być potrzebny.'),
    ('natural_one', 'Kiedy rzuciłeś kością i przypomniało Ci się Twoje odbicie w lustrze.'),
    ('initiative_master', 'Szybki w działaniu i zbyt "mądry" żeby najpierw przeczytać instrukcję.'),
    ('camp_host', 'Ogień do planszówek płonie. Stół rozłożony. Jeszcze alko i jechane.'),
    ('party_summoned', 'Przed wyruszeniem w podróż musisz zebrać drużynę.'),
    ('party_bard', 'Słowo stało się ciałem, opinia zamieszkała wśród plansz.'),
    ('coast_chronicler', 'Co zostało zapisane, zostało pograne.'),
    ('short_rest', 'Pięć minut przerwy. Trzy godziny później…'),
    ('full_party', 'Kiedy Rochan jest wołany, Rochan odpowie.'),
    ('lone_wolf', 'Kiedy najlepiej bawisz się w swoim towarzystwie.'),
    ('side_quest', 'Spontan to najlepsza forma planowania.'),
    ('guidance', 'Świat się pali, ale przynajmniej zaznaczone, że sobota Ci pasuje.'),
    ('candlekeep_sage', 'Dobrowolne przyswojenie 48 stronicowej instrukcji, żeby nie zagrać to też jest jakaś umiejętność.'),
    ('bone_breaker', 'Najlepszą formą współpracy jest agresja.'),
    ('persuasion_master', 'Ludzie śpieszą się liczyć z Twoim zdaniem, tak szybko odchodzi.'),
    ('table_rogue', 'Oszukujesz innych prawie tak dobrze jak siebie.'),
    ('dark_urge', 'Wygrana za wszelką cenę, szkoda że kosztem życia socjalnego.'),
    ('tadpole_enjoyer', 'To, że czegoś nie lubisz nie znaczy, że od razu masz przegrać.'),
    ('save_scummer', 'Tym razem na pewno się uda. To samo powiedziałeś wczoraj.'),
    ('multiclass', 'Strateg. Zdrajca. Ekonomista. Hodowca. CV robi się imponujące.'),
    ('loot_goblin', 'To nie kolekcjonowanie. To zarządzanie bardzo pokaźnym ekwipunkiem.'),
    ('tavern_brawler', 'Strategia skończyła się po drugiej kolejce. Godność chwilę później.'),
    ('quest_accepted', 'Kiedy samo zbieranie questów jest questem.'),
    ('vicious_mockery', 'To nie była recenzja. To był atak dystansowy słowem.'),
    ('fanboy', 'Obiektywizm opuścił tego podróżnika.'),
    ('hot_take', 'Prawo do własnej opinii zostało wykorzystane. Niestety.'),
    ('one_more_turn', 'Ostatnia tura to stan umysłu, nie faktyczny moment zakończenia gry.'),
    ('last_turn_hero', 'Kiedy po dramatyzowaniu i obrażeniu się na wszystkich realizujesz turę życia.'),
    ('rule_quard', 'Teraz wszyscy będą cierpieć zgodnie z regulaminem.'),
    ('long_rest', 'Rozgrywka zostanie dokończona po pełnym odpoczynku. Czyli nigdy.'),
    ('bag_of_holding', 'Nikt nie wie, gdzie to wszystko trzymasz. Skarbówka powinna się zainteresować.'),
    ('legendary_artifact', 'Stara ale jara.'),
    ('eternal_shelf_curse', 'Kupiłeś ją. Podziwiałeś ją. Kurz jest również zachwycony.'),
    ('resurrection', 'Śmierć okazała się tylko wyjątkowo długą przerwą między partiami.'),
    ('oathbreaker', 'Złamałeś przysięgę: „Nigdy więcej!”.'),
    ('glass_cannon', 'Albo z tarczą. Albo na tarczy. Nic pomiędzy.'),
    ('skill_issue', 'To gra była źle zbalansowana przeciwko Tobie. Trzy razy z rzędu.'),
    ('git_gud', 'Okazało się, że czwarta porażka nie była obowiązkowa.'),
    ('redemption_arc', 'Po wygranej już nie wydaje się taka zła.'),
    ('chosen_of_the_table', 'Zbierasz punkty jak prawdziwy szampion.'),
    ('final_boss', 'Wszyscy zgładzeni, wraz z osobą tłumaczącą zasady.'),
    ('boss_defeated', 'Po pokonaniu bossa zostało jeszcze jedno zagrożenie. Kłócenie się o punktację.'),
    ('plot_armor', 'Gracz tak dobry, że wpisany do instrukcji.'),
    ('main_character', 'Inni gracze byli niewielką częścią Twojego zwycięstwa.'),
    ('time_traveler', 'Cztery dekady. Setki zasad. Nadal ktoś pyta, czy może cofnąć ruch.'),
    ('dice_speak', 'Planowanie to objaw rozsądku. Właśnie tego zabrakło.'),
    ('friendly_fire', 'Miło przestaje być tam, gdzie zaczynają punkty zwycięstwa.'),
    ('no_save_found', 'Nie zapraszaj już Porażki do gry.'),
    ('the_absolute', 'Decyzja o głosach i wygranej zapadła jednogłośnie. Absolutnie.'),
    ('critical_success_question_mark', 'Plan się udał. Teraz pozostaje ustalić, co to się stanęło.'),
    ('hot_streak', 'Rzuty godne Michała, tylko odwrotnie.')
) as descriptions(achievement_key, description)
where achievement.achievement_key = descriptions.achievement_key;
